name: NodeJS with Webpack
on:
  push:
    branches:
      - C_DEV_FEAT

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v2
      - name: Installation des dépendances
        run: npm install
      - name: Build
        run: npm run build
      - name: Exécution des tests
        run: npm test
      - name: Archive du build
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results

# deploy:
#     needs: build-and-test
#     runs-on: ubuntu-latest
#     steps:
#       - name: Téléchargement des résultats de tests
#         uses: actions/download-artifact@v2
#         with:
#           name: test-results
#       - name: Déploiement sur le serveur de production
#         run: |
#           # Script de déploiement ici
#           echo "Déploiement de l'application sur le serveur de production."
